# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;acc_on_device-1.f95;;-O -fdump-rtl-expand -std=legacy;;
compile;acc_on_device-2-off.f95;;-O -fdump-rtl-expand -fno-openacc;;
compile;acc_on_device-2.f95;;-O -fdump-rtl-expand;;
compile;array-reduction.f90;xfail;;;
compile;array-with-dt-1.f90;;-Wuninitialized;;
compile;array-with-dt-1a.f90;;-Wuninitialized -O0;;
compile;array-with-dt-2.f90;;-Wuninitialized;;
compile;array-with-dt-3.f90;;-Wuninitialized;;
compile;array-with-dt-4.f90;;-Wuninitialized;;
compile;array-with-dt-5.f90;;-Wuninitialized;;
compile;array-with-dt-6.f90;xfail;;;
compile;assumed.f95;xfail;-fmax-errors=100;;
compile;asyncwait-1.f95;xfail;;;
compile;asyncwait-2.f95;xfail;;;
compile;asyncwait-3.f95;xfail;;;
compile;asyncwait-4.f95;xfail;;;
compile;asyncwait-5.f;;-fdump-tree-original;;
compile;atomic-1.f90;;;;
compile;atomic.f90;xfail;;;
compile;attach-descriptor.f90;;-fdump-tree-original -fdump-tree-gimple;;
compile;branch.f95;xfail;;;
compile;cache-1.f95;;-std=f2008;;
compile;cache-2.f95;xfail;-std=f2008;;
compile;classify-kernels-parloops.f95;;--param openacc-kernels=parloops -O2 -fopt-info-optimized-omp -fdump-tree-ompexp -fdump-tree-parloops1-all -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;classify-kernels-unparallelized-parloops.f95;;--param openacc-kernels=parloops -O2 -fopt-info-optimized-omp -fdump-tree-ompexp -fdump-tree-parloops1-all -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;classify-kernels-unparallelized.f95;;--param openacc-kernels=decompose -O2 -fopt-info-all-omp -fdump-tree-ompexp -fdump-tree-parloops1-all -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;classify-kernels.f95;;--param openacc-kernels=decompose -O2 -fopt-info-all-omp -fdump-tree-ompexp -fdump-tree-parloops1-all -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;classify-parallel.f95;;-O2 -fopt-info-optimized-omp -fdump-tree-ompexp -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;classify-routine-nohost.f95;;-O2 -fopt-info-optimized-omp -fdump-tree-ompexp -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;classify-routine.f95;;-O2 -fopt-info-optimized-omp -fdump-tree-ompexp -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;classify-serial.f95;;-O2 -fopt-info-optimized-omp -fdump-tree-ompexp -fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;coarray.f95;xfail;-fcoarray=single;;
compile;coarray_2.f90;xfail;-fcoarray=lib;;
compile;coindexed-1.f90;xfail;-fcoarray=single;;
compile;combined-directives-3.f90;xfail;;;
compile;combined-directives.f90;;-fdump-tree-gimple;;
compile;combined_loop.f90;;;;
compile;common-block-1.f90;xfail;;;
compile;common-block-2.f90;xfail;;;
compile;common-block-3.f90;;-fopenacc -fdump-tree-omplower --param=openacc-kernels=decompose -fopt-info-omp-all --param=openacc-privatization=noisy;;
compile;continuation-free-form.f95;xfail;;;
compile;cray-2.f95;xfail;-fcray-pointer;;
compile;cray.f95;xfail;-fcray-pointer;;
compile;critical.f95;xfail;-fcoarray=single;;
compile;data-clauses.f95;xfail;-fmax-errors=100;;
compile;data-tree.f95;;-fdump-tree-original;;
compile;declare-1.f95;xfail;;;
compile;declare-2.f95;xfail;;;
compile;declare-3.f95;;-fdump-tree-original;;
compile;deep-copy-2.f90;xfail;;;
compile;default-1.f95;;;;
compile;default-2.f;xfail;;;
compile;default-3.f95;xfail;;;
compile;default-4.f;;-fdump-tree-gimple;;
compile;default-5.f;;-fdump-tree-gimple;;
compile;default_none.f95;;;;
compile;derived-chartypes-1.f90;;-Wuninitialized;;
compile;derived-chartypes-2.f90;;-Wuninitialized;;
compile;derived-chartypes-3.f90;;-fdump-tree-gimple -Wuninitialized;;
compile;derived-chartypes-4.f90;;-fdump-tree-gimple -Wuninitialized;;
compile;derived-classtypes-1.f95;;-Wuninitialized;;
compile;derived-types-2.f90;;-Wuninitialized;;
compile;derived-types-3.f90;xfail;;;
compile;derived-types.f90;xfail;;;
compile;enter-exit-data.f95;xfail;-fmax-errors=100;;
compile;finalize-1.f;;-fdump-tree-original -fdump-tree-gimple;;
compile;firstprivate-1.f95;xfail;;;
compile;fixed-1.f;;;;
compile;fixed-2.f;xfail;-fmax-errors=100;;
compile;fixed-3.f;;;;
compile;fixed-4.f;;;;
compile;fixed-5.f;;;;
compile;gang-static.f95;;-fdump-tree-omplower;;
compile;host_data-tree.f95;;-fdump-tree-original -fdump-tree-gimple -Wuninitialized;;
compile;if.f95;xfail;;;
compile;kernels-alias-2.f95;;-O2 -fdump-tree-ealias-all;;
compile;kernels-alias-3.f95;;-O2 -fdump-tree-ealias-all;;
compile;kernels-alias-4.f95;;-O2 -fdump-tree-ealias-all;;
compile;kernels-alias.f95;;-O2 -fdump-tree-ealias-all;;
compile;kernels-decompose-1.f95;;-fopt-info-omp-all -fdump-tree-gimple --param=openacc-kernels=decompose -fdump-tree-omp_oacc_kernels_decompose --param=openacc-privatization=noisy -Wopenacc-parallelism;;
compile;kernels-decompose-2.f95;;-fopt-info-omp-all --param=openacc-kernels=decompose -O2 --param=openacc-privatization=noisy -Wopenacc-parallelism;;
compile;kernels-loop-2.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loop-data-2.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loop-data-enter-exit-2.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loop-data-enter-exit.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loop-data-update.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loop-data.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loop-inner.f95;;-O2 -fopt-info-optimized-omp;;
compile;kernels-loop-n.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loop.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-loops-adjacent.f95;;-O2;;
compile;kernels-parallel-loop-data-enter-exit.f95;;-O2 -fdump-tree-parloops1-all -fdump-tree-optimized;;
compile;kernels-tree.f95;;-fdump-tree-original --param=openacc-kernels=decompose -fdump-tree-omp_oacc_kernels_decompose -Wuninitialized;;
compile;list.f95;xfail;-fmax-errors=100;;
compile;literal.f95;xfail;;;
compile;loop-1-2.f95;xfail;-std=legacy;;
compile;loop-1.f95;xfail;-std=legacy;;
compile;loop-2-kernels-nested.f95;;;;
compile;loop-2-kernels-tile.f95;xfail;;;
compile;loop-2-kernels.f95;xfail;;;
compile;loop-2-parallel-3.f95;xfail;;;
compile;loop-2-parallel-nested.f95;;;;
compile;loop-2-parallel-tile.f95;xfail;;;
compile;loop-2-parallel.f95;xfail;;;
compile;loop-3-2.f95;xfail;-std=f2008;;
compile;loop-3.f95;xfail;-std=f2008;;
compile;loop-4.f95;xfail;;;
compile;loop-7.f95;xfail;-fmax-errors=100;;
compile;loop-tree-1.f90;;-fdump-tree-original -fdump-tree-gimple -std=f2008;;
compile;mapping-tests-1.f90;xfail;;;
compile;mapping-tests-2.f90;xfail;;;
compile;mapping-tests-3.f90;;-fdump-tree-gimple;;
compile;mapping-tests-4.f90;xfail;;;
compile;mapping-tests-5.f90;xfail;;;
compile;modules.f95;;-Wuninitialized;;
compile;multi-clause.f90;xfail;;;
compile;nested-function-1.f90;;--param=openacc-kernels=decompose -fopt-info-all-omp --param=openacc-privatization=noisy;;
compile;nested-parallelism.f90;xfail;;;
compile;nested-reductions-1-kernels.f90;;-Wuninitialized;;
compile;nested-reductions-1-parallel.f90;;-Wuninitialized;;
compile;nested-reductions-1-routine.f90;xfail;-Wuninitialized;;
compile;nested-reductions-2-kernels.f90;;-Wuninitialized;;
compile;nested-reductions-2-parallel.f90;;-Wuninitialized;;
compile;nested-reductions-2-routine.f90;xfail;-Wuninitialized;;
compile;note-parallelism.f90;;-fopt-info-optimized-omp;;
compile;omp-fixed.f;xfail;-fopenmp;;
compile;omp.f95;xfail;-fopenmp;;
compile;orphan-reductions-1.f90;xfail;;;
compile;orphan-reductions-2.f90;xfail;-fopt-info-optimized-omp -Wopenacc-parallelism;;
compile;orphan-reductions-3.f90;;-Wopenacc-parallelism;;
compile;parallel-dims-2.f90;xfail;;;
compile;parallel-kernels-clauses.f95;xfail;-fmax-errors=100;;
compile;parallel-kernels-regions.f95;xfail;;;
compile;parallel-tree.f95;;-fdump-tree-original -Wuninitialized -Wopenacc-parallelism;;
compile;parameter.f95;xfail;;;
compile;pr104717.f90;;-O1 -fstack-arrays -fipa-pta;;
compile;pr71704.f90;;;;
compile;pr72715.f90;xfail;;;
compile;pr72743.f90;;-O2;;
compile;pr77371-1.f90;;;;
compile;pr77371-2.f90;xfail;;;
compile;pr77765.f90;xfail;;;
compile;pr78027.f90;;-fopenmp -O2 -fdump-ipa-icf;;
compile;pr78260-2.f90;;-fopenacc -fdump-tree-original;;
compile;pr78260.f90;xfail;-fopenacc;;
compile;pr84217.f90;;;;
compile;pr84963.f90;;-O2;;
compile;pr85701.f90;xfail;;;
compile;pr85702.f90;xfail;;;
compile;pr85703.f90;;;;
compile;pr85879.f90;;;;
compile;pr89773.f90;;-fdump-tree-optimized-raw;;
compile;pr92793-1.f90;xfail;-fdump-tree-original-lineno -fdump-tree-gimple-lineno;;
compile;pr93329.f90;xfail;-fopenmp -fopenmp;;
compile;pr93463.f90;xfail;-fopenmp -fopenmp;;
compile;pr93464-2.f90;;-Wuninitialized -O0;;
compile;pr93464.f90;;-Wuninitialized;;
compile;pr94120-1.f90;xfail;;;
compile;pr94120-2.f90;xfail;;;
compile;pr94120-3.f90;xfail;;;
compile;private-3.f95;;-fopt-info-note-omp --param=openacc-privatization=noisy;;
compile;private-explicit-kernels-1.f95;;-fdump-tree-original -fdump-tree-gimple;;
compile;private-explicit-parallel-1.f95;;-fdump-tree-original -fdump-tree-gimple;;
compile;private-explicit-routine-1.f95;;-fdump-tree-original -fdump-tree-gimple;;
compile;private-predetermined-kernels-1.f95;;-fdump-tree-original -fdump-tree-gimple;;
compile;private-predetermined-parallel-1.f95;;-fdump-tree-original -fdump-tree-gimple;;
compile;private-predetermined-routine-1.f95;;-fdump-tree-original -fdump-tree-gimple;;
compile;privatization-1-compute-loop.f90;;-fopt-info-omp-note --param=openacc-privatization=noisy -Wuninitialized;;
compile;privatization-1-compute.f90;;-fopt-info-omp-note --param=openacc-privatization=noisy -Wuninitialized;;
compile;privatization-1-routine_gang-loop.f90;;-fopt-info-omp-note --param=openacc-privatization=noisy -Wuninitialized;;
compile;privatization-1-routine_gang.f90;;-fopt-info-omp-note --param=openacc-privatization=noisy -Wuninitialized;;
compile;pure-elemental-procedures-2.f90;xfail;;;
compile;pure-elemental-procedures.f95;xfail;-std=f2008 -fcoarray=single;;
compile;reduction-2.f95;;-fdump-tree-gimple;;
compile;reduction-3.f95;xfail;;;
compile;reduction-promotions.f90;;-fdump-tree-gimple;;
compile;reduction.f95;xfail;-fmax-errors=100;;
compile;ref_inquiry.f90;xfail;;;
compile;routine-1.f90;xfail;;;
compile;routine-2.f90;xfail;;;
compile;routine-3.f90;;;;
compile;routine-4.f90;xfail;-Wopenacc-parallelism;;
compile;routine-5.f90;xfail;;;
compile;routine-6.f90;xfail;;;
compile;routine-8.f90;xfail;;;
compile;routine-external-level-of-parallelism-1.f;;-fopt-info-optimized-omp;;
compile;routine-external-level-of-parallelism-2.f;xfail;-fopt-info-optimized-omp;;
compile;routine-intrinsic-1.f;;;;
compile;routine-intrinsic-2.f;xfail;;;
compile;routine-level-of-parallelism-1.f90;;-Wopenacc-parallelism;;
compile;routine-module-1.f90 routine-module-mod-1.f90;;-fopt-info-optimized-omp;;
compile;routine-module-2.f90 routine-module-mod-1.f90;xfail;;;
compile;routine-module-3.f90 routine-module-mod-1.f90;xfail;;;
compile;routine-multiple-directives-1.f90;;-fdump-tree-oaccloops -Wopenacc-parallelism;;
compile;routine-multiple-directives-2.f90;xfail;;;
compile;routine-multiple-lop-clauses-1.f90;xfail;;;
compile;sentinel-free-form.f95;xfail;;;
compile;several-directives.f95;xfail;;;
compile;sie.f95;xfail;-fmax-errors=100;;
compile;specification-part.f90;;;;
compile;strided-alloc-ptr.f90;xfail;;;
compile;subarrays.f95;xfail;;;
compile;substring.f90;xfail;;;
compile;tile-1.f90;xfail;;;
compile;tile-2.f90;xfail;;;
compile;tile-3.f90;;;;
compile;tile-4.f90;xfail;;;
compile;tile-lowering.f95;;-fdump-tree-original;;
compile;unexpected-end.f90;xfail;;;
compile;uninit-copy-clause.f95;;-Wuninitialized;;
compile;uninit-dim-clause.f95;;-Wuninitialized -Wopenacc-parallelism;;
compile;uninit-firstprivate-clause.f95;;-Wuninitialized;;
compile;uninit-if-clause.f95;;-Wuninitialized;;
compile;uninit-use-device-clause.f95;;-Wuninitialized;;
compile;update-if_present-1.f90;;-fdump-tree-omplower;;
compile;update-if_present-2.f90;xfail;;;
compile;update.f95;xfail;;;
compile;vector_length.f90;;;;
compile;wait.f90;;-Wuninitialized;;
compile;warn_truncated.f90;xfail;;;