# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;cost-model-pr34445.f;;;;
compile;cost-model-pr34445a.f;;-std=legacy;;
compile;fast-math-mgrid-resid.f;;-O3 --param vect-max-peeling-for-alignment=0 -fpredictive-commoning -fdump-tree-pcom-details -std=legacy;;
compile;fast-math-pr33299.f90;;;;
compile;fast-math-pr37021.f90;;;;
compile;fast-math-pr38968.f90;;;;
compile;fast-math-real8-pr40801.f90;;;;
compile;fast-math-rnflow-trs2a2.f90;;;;
compile;fast-math-vect-8.f90;;;;
compile;mask-store-1.f90;;;;
compile;no-fre-no-copy-prop-O3-pr51704.f90;;;;
compile;no-vfa-pr32377.f90;;;;
compile;no-vfa-pr32457.f90;;;;
compile;O3-bb-slp-1.f;;;;
compile;O3-bb-slp-2.f;;;;
compile;O3-pr36119.f90;;;;
compile;O3-pr39595.f;;;;
compile;O3-pr49957.f;;;;
compile;Ofast-pr50414.f90;;-std=legacy;;
compile;pr100981-1.f90;;-O3 -ftree-parallelize-loops=2 -fno-signed-zeros -fno-trapping-math;;
compile;pr106253.f;;;;
compile;pr108979.f90;;-fnon-call-exceptions;;
compile;pr19049.f90;;;;
compile;pr32377.f90;;;;
compile;pr32380.f;;-O3 -fcray-pointer;;
compile;pr33301.f;;;;
compile;pr39318.f90;;-fopenmp -fopenmp -fexceptions;;
compile;pr45714-a.f;;-O3 -march=core2 -mavx -ffast-math -mveclibabi=svml;i.86-.+-.+ x86_64-.+-.+;
compile;pr45714-b.f;;-O3 -mcpu=power7 -mno-power9-vector -mno-power8-vector -ffast-math -mveclibabi=mass;powerpc.+-.+-.+;
compile;pr46213.f90;;-O -fno-tree-loop-ivcanon -fno-tree-ccp -fno-tree-ch -finline-small-functions;;
compile;pr48329.f90;;-ffast-math;;
compile;pr50178.f90;;;;
compile;pr50412.f90;;;;
compile;pr51058-2.f90;;;;
compile;pr51058.f90;;;;
compile;pr51285.f90;;;;
compile;pr52580.f;;-std=legacy;;
compile;pr61171.f;;-Ofast;;
compile;pr62283-2.f;;-fdump-tree-slp2-details;;
compile;pr62283.f;;-fvect-cost-model=dynamic -fno-ipa-icf;;
compile;pr69466.f90;;;;
compile;pr69882.f90;;-Ofast;;
compile;pr69980.f90;;-Ofast -fno-inline;;
compile;pr70043.f90;;-Ofast -g;;
compile;pr77848.f;;-O3 -ffast-math -fdump-tree-ifcvt -fdump-tree-vect-details;;
compile;pr81303.f;;-O3 -ffast-math -floop-interchange -fdump-tree-linterchange-details;;
compile;pr83232.f90;;-funroll-loops --param vect-max-peeling-for-alignment=0 -fdump-tree-slp-details;;
compile;pr84913.f90;;;;
compile;pr86421.f90;;-fopenmp-simd;;
compile;pr89535.f90;;;;
compile;pr90681.f;;;;
compile;pr90913.f90;;-O3 -ffast-math;;
compile;pr95403.f;;;;
compile;pr96920.f90;;;;
compile;pr97761.f90;;-O1;;
compile;pr99656.f90;;-march=armv8.3-a -O1 -ftree-slp-vectorize;aarch64.+-.+-.+;
compile;pr99721.f90;;-O3;;
compile;pr99746.f90;;;;
compile;pr99807.f90;;;;
compile;pr99825.f90;;;;
compile;pr99924.f90;;;;
compile;vect-1.f90;;;;
compile;vect-2.f90;;--param vect-max-peeling-for-alignment=0;;
compile;vect-3.f90;;--param vect-max-peeling-for-alignment=0;;
compile;vect-4.f90;;--param vect-epilogues-nomask=0 --param vect-max-peeling-for-alignment=0;;
compile;vect-5.f90;;-fno-tree-loop-distribute-patterns --param vect-max-peeling-for-alignment=0;;
compile;vect-6.f;;;;
compile;vect-7.f90;;;;
compile;vect-8-epilogue.F90;;-finline-matmul-limit=0 --param vect-epilogues-nomask=1;;
compile;vect-8.f90;;-fno-tree-loop-distribute-patterns -finline-matmul-limit=0;;
compile;vect-9.f90;;-Ofast;;
compile;vect-do-concurrent-1.f90;;-O3 -fopt-info-vec-optimized;;
compile;vect-gems.f90;;;;
run;pr107254.f90;;;;
run;pr60510.f;;-fno-inline -ffast-math;;
run;pr85853.f90;;-fno-tree-loop-vectorize;;
run;vect-alias-check-1.F90;;-fno-inline;;