# This file was generated by update-test-config.py
#
#                            DO NOT EDIT THIS FILE
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;cost-model-pr34445.f;;;;
compile;cost-model-pr34445a.f;;;;
compile;fast-math-mgrid-resid.f;;-O3;;
compile;fast-math-pr33299.f90;;;;
compile;fast-math-pr37021.f90;;;;
compile;fast-math-pr38968.f90;;;;
compile;fast-math-real8-pr40801.f90;;;;
compile;fast-math-rnflow-trs2a2.f90;;;;
compile;fast-math-vect-8.f90;;;;
compile;mask-store-1.f90;;;;
compile;no-fre-no-copy-prop-O3-pr51704.f90;;;;
compile;no-vfa-pr32377.f90;;;;
compile;no-vfa-pr32457.f90;;;;
compile;O3-bb-slp-1.f;;;;
compile;O3-bb-slp-2.f;;;;
compile;O3-pr36119.f90;;;;
compile;O3-pr39595.f;;;;
compile;O3-pr49957.f;;;;
compile;Ofast-pr50414.f90;;;;
compile;pr100981-1.f90;;-O3 -fno-signed-zeros;;
compile;pr106253.f;;;;
compile;pr107254.f90;;;;
compile;pr108979.f90;;;;
compile;pr110451.f;;-ffast-math;;
compile;pr114736.f90;;-O3;;
compile;pr115528.f;;;;
compile;pr115710.f90;;-Ofast;;
compile;pr116956.f90;;;;
compile;pr19049.f90;;;;
compile;pr32377.f90;;;;
compile;pr32380.f;;-O3;;
compile;pr33301.f;;;;
compile;pr39318.f90;;-fopenmp -fopenmp;;
compile;pr45714-a.f;;-O3 -march=core2 -ffast-math;i.86-.+-.+ x86_64-.+-.+;
compile;pr45714-b.f;;-O3 -mdejagnu-cpu=power7 -ffast-math;powerpc.+-.+-.+;
compile;pr46213.f90;;-O;;
compile;pr48329.f90;;-ffast-math;;
compile;pr49955.f;;-ffast-math;;
compile;pr50178.f90;;;;
compile;pr50412.f90;;;;
compile;pr51058-2.f90;;;;
compile;pr51058.f90;;;;
compile;pr51285.f90;;;;
compile;pr52580.f;;;;
compile;pr60510.f;;-ffast-math;;
compile;pr61171.f;;-Ofast;;
compile;pr62283-2.f;;;;
compile;pr62283.f;;;;
compile;pr68855.f90;;;;
compile;pr69466.f90;;;;
compile;pr69882.f90;;-Ofast;;
compile;pr69980.f90;;-Ofast;;
compile;pr70043.f90;;-Ofast -g;;
compile;pr77848.f;;-O3 -ffast-math;;
compile;pr81303.f;;-O3 -ffast-math;;
compile;pr83232.f90;;;;
compile;pr84913.f90;;;;
compile;pr85853.f90;;;;
compile;pr86421.f90;;;;
compile;pr89535.f90;;;;
compile;pr90681.f;;;;
compile;pr90913.f90;;-O3 -ffast-math;;
compile;pr95403.f;;;;
compile;pr96920.f90;;;;
compile;pr97761.f90;;-O1;;
compile;pr99656.f90;;-march=armv8.3-a -O1;aarch64.+-.+-.+;
compile;pr99721.f90;;-O3;;
compile;pr99746.f90;;;;
compile;pr99807.f90;;;;
compile;pr99825.f90;;;;
compile;pr99924.f90;;;;
compile;vect-1.f90;;;;
compile;vect-10.f90;;;;
compile;vect-2.f90;;;;
compile;vect-3.f90;;;;
compile;vect-4.f90;;;;
compile;vect-5.f90;;;;
compile;vect-6.f;;;;
compile;vect-7.f90;;;;
compile;vect-8-epilogue.F90;;vect-epilogues-nomask=1;;
compile;vect-8.f90;;;;
compile;vect-9.f90;;-Ofast;;
compile;vect-alias-check-1.F90;;;;
compile;vect-do-concurrent-1.f90;;-O3;;
compile;vect-early-break_1-pr113808.f90;;;;
compile;vect-gems.f90;;;;