! Test for TOKENIZE Fortran 2023 Standard intrinsic subroutine.

SUBROUTINE PRINTFORM1 (STR, M, N, NM)
  INTEGER :: M, N, I
  CHARACTER (LEN=M), DIMENSION(n) :: STR
  CHARACTER(LEN=12) :: NM

  PRINT *, NM
  IF (N < 1) THEN
    PRINT ("(T7,A1,A,A1)"), '"', "", '"'
  ELSE
    DO I = 1, N
      PRINT ("(T7,A1,A,A1)"), '"', STR(I), '"'
    ENDDO
  ENDIF

END

SUBROUTINE PRINTFORM2 (FST, LST)
  INTEGER, ALLOCATABLE, DIMENSION(:) :: FST, LST
  INTEGER :: N, I

  N = SIZE(FST)
  PRINT ("(T4,A7,A7)"), "FIRST", "LAST"
  IF (N < 1) THEN
    PRINT ("(T4,I7,I7)"), 0, 0
  ELSE
    DO I = 1, N
      PRINT ("(T4,I7,I7)"), FST(I), LST(I)
    ENDDO
  ENDIF

END

SUBROUTINE DO_TESTS (STRING, SET, NOTE)
  CHARACTER (LEN=:), ALLOCATABLE :: STRING, SET, NOTE
  INTEGER, ALLOCATABLE, DIMENSION(:) :: FIRST, LAST
  CHARACTER (LEN=:), ALLOCATABLE, DIMENSION(:) :: TOKENS, SEPARATOR
  CHARACTER(LEN=12) :: TKN = "  TOKENS:"
  CHARACTER(LEN=12) :: SPR = "  SEPARATOR:"
  INTEGER :: CASES = 0;
  INTEGER P, ISTART, IEND
  SAVE CASES

  INTERFACE 
    SUBROUTINE PRINTFORM1 (STR, M, N, NM)
      INTEGER :: M, N
      CHARACTER (LEN=M), DIMENSION(N) :: STR
      CHARACTER(LEN=12) :: NM
    ENDSUBROUTINE

    SUBROUTINE PRINTFORM2 (FST, LST)
      INTEGER, ALLOCATABLE, DIMENSION(:) :: FST, LST
    ENDSUBROUTINE
  ENDINTERFACE

  CASES = CASES + 1
  PRINT *, "==== Case ", cases, ": ", NOTE, " ===="
  PRINT *, ' STRING = "', STRING, '"'
  PRINT *, ' SET = "', SET, '"'
  PRINT *, ''

  PRINT *, "  ---- Test", CASES, "- 4: TOKENIZE with FIRST and LAST ----"
  CALL TOKENIZE(STRING, SET, FIRST, LAST)
  CALL PRINTFORM2(FIRST, LAST)
  DEALLOCATE (FIRST, LAST)

  PRINT *, "  ---- Test", CASES, "- 5: TOKENIZE with TOKENS, but no SEPARATOR ----"
  CALL TOKENIZE(STRING, SET, TOKENS)
  CALL PRINTFORM1(TOKENS, SIZEOF(TOKENS) / MAX(1,SIZE(TOKENS)), SIZE(TOKENS), TKN)
  DEALLOCATE (TOKENS)

  PRINT *, "  ---- Test", CASES, "- 6: TOKENIZE with TOKENS and SEPARATOR ----"
  CALL TOKENIZE(STRING, SET, TOKENS, SEPARATOR)
  CALL PRINTFORM1(TOKENS, SIZEOF(TOKENS) / MAX(1,SIZE(TOKENS)), SIZE(TOKENS), TKN)
  CALL PRINTFORM1(SEPARATOR, SIZEOF(SEPARATOR) / MAX(1,SIZE(SEPARATOR)), SIZE(SEPARATOR), SPR)
  DEALLOCATE (TOKENS, SEPARATOR)

  10 FORMAT (T7, '"', A, '"')

END

PROGRAM TOKENIZE01
  CHARACTER (LEN=:), ALLOCATABLE :: STRING, SET, NOTE

  INTERFACE 
    SUBROUTINE DO_TESTS (STRING, SET, NOTE)
      CHARACTER(LEN=:), ALLOCATABLE :: STRING, SET, NOTE
    ENDSUBROUTINE
  ENDINTERFACE

! Case 1
  STRING = "first,second third"
  SET = ", :;"
  NOTE = "common case"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(STRING, NOTE)

! Case 2
  STRING = ",first,second third;"
  NOTE = "first and last characters are delimiters"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(STRING, NOTE)

! Case 3
  STRING = ",first,second; ,:;third,"
  NOTE = "multiple delimiters in a row"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(STRING, NOTE)

! Case 4
  STRING = ",first,second;third_third"
  NOTE = "the last token is the longest"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(SET, NOTE)

! Case 5
  SET = ""
  NOTE = "SET is zero size"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(STRING, SET, NOTE)

! Case 6
  STRING = "f,s;t"
  SET = ", :;"
  NOTE = "one character tokens"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(STRING, NOTE)

! Case 7
  STRING = ""
  NOTE = "STRING is zero size"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(STRING, SET, NOTE)

! Case 8
  STRING = ""
  SET = ""
  NOTE = "both STRING and SET are zero size"
  CALL DO_TESTS (STRING, SET, NOTE)
  DEALLOCATE(STRING, SET, NOTE)
END PROGRAM TOKENIZE01
