"""Test module to collect compile-time metrics (time and peak memory). This
reads the *.o.time.list and *.link.time.list path-list files generated by the
build-stage aggregate-compile-time.py script."""
from litsupport.modules import timeit
import os


def _getCompileTime(context):
    exe_name = os.path.basename(context.executable)
    test_dir = os.path.dirname(context.executable)

    compile_time = 0.0
    link_time = 0.0
    compile_maxrss = 0
    link_maxrss = 0

    # ------------------------------------------------------------------
    # Compile time: sum every .o.time file listed in <exe>.o.time.list.
    # ------------------------------------------------------------------
    o_time_list = os.path.join(test_dir, exe_name + ".o.time.list")
    if os.path.isfile(o_time_list):
        with open(o_time_list) as f:
            for line in f:
                path = line.rstrip("\n")
                if not path:
                    continue
                try:
                    with open(path) as fd:
                        contents = fd.read()
                    compile_time += timeit.getUserTimeFromContents(contents)
                    compile_maxrss = max(compile_maxrss,
                                        timeit.getMaxRSSFromContents(contents))
                except OSError:
                    pass

    # ------------------------------------------------------------------
    # Link time: read the single file listed in <exe>.link.time.list.
    # ------------------------------------------------------------------
    link_time_list = os.path.join(test_dir, exe_name + ".link.time.list")
    if os.path.isfile(link_time_list):
        with open(link_time_list) as f:
            for line in f:
                path = line.rstrip("\n")
                if not path:
                    continue
                try:
                    with open(path) as fd:
                        contents = fd.read()
                    link_time += timeit.getUserTimeFromContents(contents)
                    link_maxrss = max(link_maxrss,
                                     timeit.getMaxRSSFromContents(contents))
                except OSError:
                    pass

    return {
        "compile_time": compile_time,
        "link_time": link_time,
        "compile_maxrss": compile_maxrss,
        "link_maxrss": link_maxrss,
    }


def mutatePlan(context, plan):
    plan.metric_collectors.append(_getCompileTime)
