"""Test module to collect compile-time metrics (time and peak memory). This
finds and summarizes the *.time files generated by the build."""
from litsupport.modules import timeit
import os


def _getCompileTime(context):
    # We compile multiple benchmarks in the same directory in SingleSource
    # mode. Only look at compiletime files starting with the name of our test.
    prefix = ""
    if context.config.single_source:
        prefix = "%s." % os.path.basename(context.executable)

    compile_time = 0.0
    link_time = 0.0
    compile_maxrss = 0
    link_maxrss = 0
    dir = os.path.dirname(context.test.getFilePath())
    for path, subdirs, files in os.walk(dir):
        for file in files:
            if file.endswith(".o.time") and file.startswith(prefix):
                fullpath = os.path.join(path, file)
                with open(fullpath) as fd:
                    contents = fd.read()
                compile_time += timeit.getUserTimeFromContents(contents)
                compile_maxrss = max(compile_maxrss,
                                     timeit.getMaxRSSFromContents(contents))
            if file.endswith(".link.time") and file.startswith(prefix):
                fullpath = os.path.join(path, file)
                with open(fullpath) as fd:
                    contents = fd.read()
                link_time += timeit.getUserTimeFromContents(contents)
                link_maxrss = max(link_maxrss,
                                  timeit.getMaxRSSFromContents(contents))
    return {
        "compile_time": compile_time,
        "link_time": link_time,
        "compile_maxrss": compile_maxrss,
        "link_maxrss": link_maxrss,
    }


def mutatePlan(context, plan):
    plan.metric_collectors.append(_getCompileTime)
