# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;a.1.1.f90;;;;
compile;a.11.1.f90;;;;
compile;a.11.2.f90;;;;
compile;a.11.3.f90;;;;
compile;a.11.4.f90;;;;
compile;a.11.5.f90;;;;
compile;a.11.6.f90;;;;
compile;a.11.7.f90;;;;
compile;a.12.1.f90;;;;
compile;a.13.1.f90;;;;
compile;a.14.1.f90;;;;
compile;a.17.1.f90;;;;
compile;a.17.2.f90;;;;
compile;a.17.3.f90;;;;
compile;a.21.2.f90;;;;
compile;a.21.3.f90;;;;
compile;a.22.1.f90;;;;
compile;a.22.4.f90;xfail;;;
compile;a.22.5.f90;xfail;;;
compile;a.22.6.f90;;;;
compile;a.23.1.f90;;;;
compile;a.23.2.f90;;;;
compile;a.23.3.f90;;;;
compile;a.23.4.f90;xfail;;;
compile;a.23.5.f90;xfail;;;
compile;a.24.1.f90;xfail;;;
compile;a.25.1.f90;;;;
compile;a.26.2.f90;;;;
compile;a.27.1.f90;;;;
compile;a.30.1.f90;;;;
compile;a.31.1.f90;;;;
compile;a.31.2.f90;;;;
compile;a.31.3.f90;xfail;;;
compile;a.32.1.f90;;;;
compile;a.33.1.f90;;;;
compile;a.33.2.f90;;;;
compile;a.33.4.f90;;;;
compile;a.34.1.f90;;;;
compile;a.34.2.f90;;;;
compile;a.35.1.f90;xfail;;;
compile;a.35.2.f90;;;;
compile;a.35.3.f90;xfail;;;
compile;a.35.4.f90;xfail;;;
compile;a.35.5.f90;xfail;;;
compile;a.35.6.f90;xfail;;;
compile;a.36.1.f90;;;;
compile;a.37.1.f90;;;;
compile;a.37.2.f90;;;;
compile;a.6.1.f90;;-std=legacy;;
compile;a.6.2.f90;xfail;-std=legacy;;
compile;a.7.1.f90;;;;
compile;a.7.2.f90;;;;
compile;a.8.1.f90;;;;
compile;a.9.1.f90;;;;