#!/usr/bin/env python
# -*- Python -*-

import spec

class SPEC2006_462_libquantum(spec.TestModule):
    year = '2006'
    category = 'int'
    benchmark = '462.libquantum'

    train_input_set = []
    train_output_set = ['train/output/train.out']
    train_args = ['143 25 > 462.libquantum.143.out 2> 462.libquantum.143.err']
    train_cmp_cmds = ['diff 462.libquantum.143.out train.out --strip-trailing-cr > 462.libquantum.143.cmp']
    ref_input_set = []
    ref_output_set = ['ref/output/ref.out']
    ref_args = ['1397 8 > 462.libquantum.1397.out 2> 462.libquantum.1397.err']
    ref_cmp_cmds = ['diff 462.libquantum.1397.out ref.out --strip-trailing-cr > 462.libquantum.1397.cmp']

# This is the only required entry point to the module.
test_class = SPEC2006_462_libquantum

# This is not required, but allows users with LNT in the environment (required
# for initial imports to work) to execute this test directly.
if __name__ == '__main__':
    test_class().main()
