# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
assemble;pr46629_0.f90;;-O2 -flto -ftree-vectorize;;
compile;20091015-1_1.f;;;;
compile;20091015-1_2.f;;;;
compile;pr40724_0.f;;;;
compile;pr40724_1.f;;;;
compile;pr40725_0.f03;;;;
compile;pr41069_1.f90;;;;
compile;pr41069_2.f90;;;;
compile;pr41521_1.f90;;;;
compile;pr41576_1.f90;;;;
compile;pr47839_1.f90;;;;
compile;pr87689_1.f;;;;
link;20091015-1_0.f;;-w;;
link;20091016-1_0.f90;;-flto -g -fPIC -r -flinker-output=nolto-rel;;
link;20091028-1_0.f90;;-r -nostdlib -finline-functions -flinker-output=nolto-rel -Wno-lto-type-mismatch;;
link;20091028-2_0.f90;;-r -nostdlib -finline-functions -flinker-output=nolto-rel -Wno-lto-type-mismatch;;
link;20100110-1_0.f90;;-O1 -flto;;
link;bind-c-char_0.f90;;-O0 -flto;;
link;pr41069_0.f90;;;;
link;pr41521_0.f90;;-g -flto -Wno-lto-type-mismatch;;
link;pr41764_0.f;;;;
link;pr45586-2_0.f90;;;;
link;pr45586_0.f90;;;;
link;pr46036_0.f90;;-O -flto -ftree-vectorize;;
link;pr46911_0.f;;-O2 -flto -g -r -nostdlib -flinker-output=nolto-rel;;
link;pr47839_0.f90;;-g -flto -r -nostdlib -flinker-output=nolto-rel;;
link;pr60635_0.f90;;-Wno-lto-type-mismatch;;
link;pr79108_0.f90;;-Ofast -flto --param ggc-min-expand=0 --param ggc-min-heapsize=0 -r;;
link;pr84645_0.f90;;-flto -g0 -g;;
link;pr89084_0.f90;;-O0 -flto;;
run;20100222-1_0.f03;;;;
run;bind_c-1_0.f90;;-O3 -flto;;
run;bind_c-2_0.f90;;-O3 -flto;;
run;bind_c-2b_0.f90;;-O3 -flto;;
run;bind_c-3_0.f90;;-O3 -flto;;
run;bind_c-4_0.f90;;-O3 -flto;;
run;bind_c-5_0.f90;;-O3 -flto;;
run;bind_c-6_0.f90;;-O3 -flto;;
run;pr41576_0.f90;;-O2 -flto -Werror -Wno-lto-type-mismatch;;
run;pr87689_0.f;;;;