LEVEL = ../../..
PROG = hexxagon
REQUIRES_EH_SUPPORT = 1
LDFLAGS += -lstdc++ -lreadline -ltermcap
LIBS += -lstdc++ -lreadline -ltermcap
STDIN_FILENAME=$(BUILD_SRC_DIR)/input
include ../../Makefile.multisrc
