set(OPTFLAGS "${OPTFLAGS} -O3 -g")

set(CMAKE_C_FLAGS_RELWITHDEBINFO  "${OPTFLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO  "${OPTFLAGS}" CACHE STRING "")
set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "")
