# SingleSource/UnitTests/Vector/NEON/Makefile

DIRS = 
LEVEL = ../../../..

ifdef BENCHMARKING_ONLY
PROGRAMS_TO_SKIP += simple
endif

include $(LEVEL)/SingleSource/Makefile.singlesrc

CFLAGS += -std=c99
