LEVEL=../../../..
PROG=anagram
#OBJS = anagram.o
RUN_OPTIONS = words 
STDIN_FILENAME = input.OUT

include ../Makefile.multisrc

#test:
#	$(SIM) ./anagram words < input.in > FOO
#	$(DIFF) FOO input.OUT
#	rm -f FOO
