# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;alloc_comp_2.f90;;;;
compile;alloc_comp_3.f90;;;;
compile;array_temporary-1.f90;;;;
compile;array_temporary.f90;;-Warray-temporaries;;
compile;data_1.f90;xfail;;;
compile;dummy_2.f90;;;;
compile;fail_image_1.f08;xfail;;;
compile;failed_images_1.f08;xfail;;;
compile;image_status_1.f08;xfail;;;
compile;stopped_images_1.f08;xfail;;;
link;codimension_2.f90 codimension_2a.f90 codimension_2b.f90;;;;
run;alloc_comp_1.f90;;;;
run;alloc_comp_4.f90;;;;
run;alloc_comp_5.f90;;;;
run;allocate_errgmsg.f90;;;;
run;atomic_1.f90;;;;
run;atomic_2.f90;;;;
run;coarray_allocated.f90;;-fdump-tree-original;;
run;codimension.f90;;;;
run;codimension_3.f90;;;;
run;coindexed_1.f90;;;;
run;collectives_1.f90;;;;
run;collectives_2.f90;;;;
run;collectives_3.f90;;;;
run;collectives_4.f90;;;;
run;cosubscript_1.f90;;;;
run;dummy_1.f90;;;;
run;event_1.f90;;;;
run;event_2.f90;;;;
run;event_3.f08;;;;
run;event_4.f08;;;;
run;fail_image_2.f08;;;;
run;failed_images_2.f08;;;;
run;get_array.f90;;;;
run;get_to_indexed_array_1.f90;;;;
run;get_to_indirect_array.f90;;;;
run;image_index_1.f90;;;;
run;image_index_2.f90;;;;
run;image_index_3.f90;;-fdefault-integer-8;;
run;image_status_2.f08;;;;
run;lib_realloc_1.f90;;;;
run;lock_1.f90;;;;
run;lock_2.f90;;;;
run;move_alloc_1.f90;;;;
run;poly_run_1.f90;;;;
run;poly_run_2.f90;;;;
run;poly_run_3.f90;;;;
run;pr107441-caf.f90;;;;
run;pr93671.f90;;;;
run;ptr_comp_1.f08;;;;
run;ptr_comp_2.f08;;;;
run;ptr_comp_3.f08;;;;
run;ptr_comp_4.f08;;;;
run;registering_1.f90;;;;
run;scalar_alloc_1.f90;;;;
run;scalar_alloc_2.f90;;;;
run;send_array.f90;;;;
run;send_char_array_1.f90;;;;
run;sendget_array.f90;;;;
run;stopped_images_2.f08;;;;
run;subobject_1.f90;;;;
run;sync_1.f90;;;;
run;sync_3.f90;xfail;-fcheck=all;;
run;this_image_1.f90;;;;
run;this_image_2.f90;;;;