LEVEL = ../../..
PROG     = spiff
CPPFLAGS = 
CFLAGS   = 
LDFLAGS  =

RUN_OPTIONS = $(PROJ_SRC_DIR)/Sample.1 $(PROJ_SRC_DIR)/Sample.2
#RUN_OPTIONS = ./Sample.3 ./Sample.4
#RUN_OPTIONS = ./one ./two
# you get the idea...

include ../../Makefile.multisrc

