LEVEL = ../../..
PROG     = siod
CPPFLAGS = -D__USE_MISC -D__USE_GNU -D__USE_SVID -D__USE_XOPEN_EXTENDED -D__USE_XOPEN -Dunix
LDFLAGS  = -lm -ldl $(TOOLLINKOPTS)

RUN_OPTIONS = -v1 $(PROJ_SRC_DIR)/test.scm

include ../../Makefile.multisrc

