
LEVEL = ../../../../..
PROG     = siod
CPPFLAGS = -D__USE_MISC -D__USE_GNU -D__USE_SVID -D__USE_XOPEN_EXTENDED -D__USE_XOPEN
LDFLAGS  = -lm -ldl -lcrypt

RUN_OPTIONS = $(BUILD_SRC_DIR)/test.scm

include ../../Makefile.multisrc

