
LEVEL = ../../../../..
PROG     = siod
CPPFLAGS = -D__USE_MISC -D__USE_GNU -D__USE_SVID -D__USE_XOPEN_EXTENDED -D__USE_XOPEN -Dunix
LDFLAGS  = -lm -ldl

RUN_OPTIONS = -v1 $(BUILD_SRC_DIR)/test.scm

include ../../Makefile.multisrc

