# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;block-1.f90;;;;
compile;block-2.f;;-std=legacy;;
compile;block-3.f90;;;;
compile;block-4.f90;;;;
compile;id-1.f90;;;;
compile;id-10.f90;;;;
compile;id-11.f;;;;
compile;id-12.f;;;;
compile;id-13.f;;;;
compile;id-14.f;;;;
compile;id-15.f;;;;
compile;id-16.f;;;;
compile;id-17.f;;;;
compile;id-18.f90;;;;
compile;id-19.f;;-std=legacy;;
compile;id-2.f90;;;;
compile;id-20.f;;-O3 -ffast-math -std=legacy;;
compile;id-21.f;;;;
compile;id-22.f;;-O3 -ffast-math;;
compile;id-23.f;;;;
compile;id-24.f;;;;
compile;id-25.f;;;;
compile;id-26.f03;;-fcray-pointer -floop-nest-optimize;;
compile;id-27.f90;;-Ofast -std=legacy;;
compile;id-28.f90;;;;
compile;id-3.f90;;;;
compile;id-4.f90;;;;
compile;id-5.f;;;;
compile;id-6.f;;;;
compile;id-7.f;;;;
compile;id-8.f;;;;
compile;id-9.f;;;;
compile;id-pr43354.f;;;;
compile;id-pr45370.f90;;;;
compile;id-pr46994.f90;;-O -ffast-math -fgraphite-identity -fno-tree-dce;;
compile;id-pr46995.f90;;-O -ffast-math -fgraphite-identity -fno-tree-dce;;
compile;id-pr47691.f;;-O -fgraphite-identity -ffast-math -fno-tree-scev-cprop;;
compile;interchange-1.f;;;;
compile;interchange-2.f;;;;
compile;interchange-3.f90;;;;
compile;interchange-4.f;;;;
compile;interchange-5.f;;;;
compile;pr107865.f90;;-O1 -floop-parallelize-all -ftree-parallelize-loops=2;;
compile;pr14741.f90;;-O3 -ffast-math -floop-nest-optimize -floop-block -fdump-tree-graphite-all;;
compile;pr29290.f90;;-O3 -ftree-loop-linear;;
compile;pr36286.f90;;-O1 -ftree-loop-linear;;
compile;pr36922.f;;-O2 -ftree-loop-linear;;
compile;pr37852.f90;;-O2;;
compile;pr37857.f90;;-O2;;
compile;pr37980.f90;;-O2;;
compile;pr38083.f90;;-O3;;
compile;pr38459.f90;;-O2 -fgraphite-identity;;
compile;pr38953.f90;;-O3 -fgraphite-identity;;
compile;pr39516.f;;-O2 -ftree-loop-linear;;
compile;pr40982.f90;;-O3 -fgraphite-identity -floop-nest-optimize;;
compile;pr41924.f90;;-O2 -fgraphite-identity;;
compile;pr42050.f90;;-O2 -fgraphite-identity;;
compile;pr42180.f90;;-ffast-math -O2 -fgraphite-identity;;
compile;pr42181.f90;;-O1 -fgraphite;;
compile;pr42185.f90;;-fgraphite -O -ffast-math;;
compile;pr42186.f90;;-fgraphite-identity -g -O3 -ffast-math;;
compile;pr42285.f90;;-O2 -floop-nest-optimize;;
compile;pr42326-1.f90;;-O2 -floop-parallelize-all -fprefetch-loop-arrays -msse2;i.86-.+-.+ x86_64-.+-.+;
compile;pr42326.f90;;-O2 -floop-strip-mine -fprefetch-loop-arrays -msse2;i.86-.+-.+ x86_64-.+-.+;
compile;pr42334-1.f;;-O2 -floop-nest-optimize;;
compile;pr42334.f90;;-O2 -floop-nest-optimize -ftree-loop-distribution;;
compile;pr42393-1.f90;;-O2 -fgraphite-identity -fno-loop-block -fno-loop-interchange -fno-loop-strip-mine;;
compile;pr42393.f90;;-O2 -fgraphite-identity -fno-loop-block -fno-loop-interchange -fno-loop-strip-mine;;
compile;pr42732.f;;-O2 -fgraphite-identity;;
compile;pr43097.f;;-O2 -fgraphite-identity;;
compile;pr43349.f;;-O2 -floop-nest-optimize;;
compile;pr45758.f90;;-O3 -floop-block;;
compile;pr47019.f;;-O -ftree-pre -fgraphite-identity -fno-tree-copy-prop;;
compile;PR53852.f90;;-floop-nest-optimize -O2 -ffast-math;;
compile;pr59586.f;;-Ofast -floop-parallelize-all;;
compile;pr59817.f;;-O2 -floop-nest-optimize;;
compile;PR67518.f90;;-floop-nest-optimize -O2 -ffast-math;;
compile;pr68279.f90;;-std=legacy -floop-nest-optimize -O2;;
compile;pr68335.f90;;-O2 -floop-nest-optimize;;
compile;pr68453.f90;;-floop-nest-optimize -O2;;
compile;pr68550-1.f90;;-floop-nest-optimize -O2;;
compile;pr68550-2.f90;;-floop-nest-optimize -fcheck=bounds -O1;;
compile;pr68692.f90;;-floop-nest-optimize -O3;;
compile;pr68693.f90;;-floop-nest-optimize -O2;;
compile;pr68715.f90;;-floop-nest-optimize -O1;;
compile;pr69728.f90;;-O3 -floop-nest-optimize;;
compile;pr71351.f90;;-O2 -floop-nest-optimize;;
compile;pr71898.f90;;-floop-nest-optimize -O1;;
compile;pr82449.f;;-O2 -floop-nest-optimize -std=legacy;;
compile;pr82451.f;;-O2 -floop-nest-optimize;;
compile;pr82672.f90;;-O2 -floop-nest-optimize;;
compile;pr83887.f;;-O2 -floop-nest-optimize;;
compile;pr83887.f90;;-O -floop-nest-optimize;;
compile;pr83963.f;;-O -floop-nest-optimize;;
compile;pr84223.f90;;-fgraphite-identity -O1 --param sccvn-max-alias-queries-per-access=0;;
compile;pr89182.f90;;-O3 -fgraphite-identity --param max-completely-peeled-insns=8;;
compile;pr90240.f;;-O1 -floop-nest-optimize;;
compile;pr93439.f90;;-O2 -floop-parallelize-all -floop-unroll-and-jam -ftree-parallelize-loops=2;;
compile;run-id-1.f;;;;
compile;run-id-2.f90;;;;
compile;scop-1.f;;;;
compile;vect-pr40979.f90;;;;
compile;vect-pr94043.f90;;-O3 -ftree-parallelize-loops=2 -fno-tree-dce;;
run;pr29581.f90;;-ftree-loop-linear;;
run;pr29832.f90;;-ftree-loop-linear;;
run;pr68565.f90;;-floop-nest-optimize;;
run;run-id-3.f90;;-ffrontend-optimize -floop-nest-optimize;;