# This file was generated by update-test-config.py
#
#                            DO NOT EDIT THIS FILE
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;large_4.f90;;;;
compile;pr77372.f90;;;;
compile;pr77507.f90;;;;
run;comparisons_1.f90;;;;
run;comparisons_2.f90;;;;
run;comparisons_3.F90;;-ffree-line-length-none;;
run;dec_math_1.f90;;-cpp -std=gnu;;
run;fma_1.f90;;;;
run;ieee_1.F90;;-ffree-line-length-none;;
run;ieee_10.f90;;-ffpe-trap=overflow,invalid;;
run;ieee_11.F90;;;;
run;ieee_12.f90;;;;
run;ieee_2.f90;;;;
run;ieee_3.f90;;;;
run;ieee_4.f90;;;;
run;ieee_5.f90;;;;
run;ieee_6.f90;;;;
run;ieee_7.f90;;;;
run;ieee_8.f90;;;;
run;ieee_9.f90;;;;
run;intrinsics_1.f90;;-fno-range-check;;
run;intrinsics_2.F90;;-fno-range-check;;
run;large_1.f90;;;;
run;large_2.f90;;;;
run;large_3.F90;;-ffree-line-length-none;;
run;minmax_1.f90;;;;
run;minmax_2.f90;;;;
run;minmax_3.f90;;;;
run;minmax_4.f90;;;;
run;modes_1.f90;;;;
run;rounding_1.f90;;;;
run;rounding_2.f90;;;;
run;rounding_3.f90;;;;
run;signaling_1.f90 signaling_1_c.c;;-w;;i386-.+-.+ ppc64le-.+-.+ powerpc-.+-.+
run;signaling_2.f90 signaling_2_c.c;;-w;;i386-.+-.+ ppc64le-.+-.+ powerpc-.+-.+
run;signaling_3.f90;;;;i386-.+-.+ ppc64le-.+-.+ powerpc-.+-.+
run;signbit_1.f90;;;;
run;underflow_1.f90;;;;