# SingleSource/UnitTests/Vector/AVX512/Makefile

DIRS = 
LEVEL = ../../../..
CFLAGS += -fms-extensions -march=skylake-avx512
LDFLAGS += -lm

include $(LEVEL)/SingleSource/Makefile.singlesrc

TARGET_FLAGS += -march=skylake-avx512
LCCFLAGS += -march=skylake-avx512
