# MultiSource Makefile:  Build all subdirectories automatically

LEVEL = ../../..
PARALLEL_DIRS  := $(filter-out %-disabled/, $(sort $(filter-out CVS/, $(wildcard */))))

include $(LEVEL)/test/Programs/Makefile.programs
