# MultiSource Makefile:  Build all subdirectories automatically

LEVEL = ..
PARALLEL_DIRS  := Applications Benchmarks
ifndef BENCHMARKING_ONLY
PARALLEL_DIRS += UnitTests
endif

include $(LEVEL)/Makefile.programs

