LEVEL = ../../..
PROG = make_dparser
Sources=make_dparser.c write_ctables.c gram.c lex.c lr.c arg.c parse.c scan.c symtab.c util.c grammar.g.c
CPPFLAGS =  -DD_BUILD_VERSION=5725
RUN_OPTIONS="-v $(BUILD_SRC_DIR)/grammar.g"
include ../../Makefile.multisrc
