# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;12002.f;;;;
compile;12632.f;;-fbounds-check;;
compile;13060.f;;;;
compile;19981216-0.f;;-std=legacy;;
compile;19990218-0.f;xfail;;;
compile;19990218-1.f;xfail;;;
compile;19990305-0.f;;;;
compile;19990419-0.f;;;;
compile;19990502-0.f;;;;
compile;19990502-1.f;;;;
compile;19990525-0.f;;-std=legacy;;
compile;19990826-1.f;;;;
compile;19990826-3.f;;-std=legacy;;
compile;19990905-0.f;;;;
compile;19990905-1.f;xfail;;;
compile;19990905-2.f;;;;
compile;20000412-1.f;;;;
compile;20000511-1.f;;;;
compile;20000511-2.f;;;;
compile;20000518.f;;;;
compile;20000601-1.f;;;;
compile;20000601-2.f;;;;
compile;20000629-1.f;;;;
compile;20000630-2.f;;-std=legacy;;
compile;20010115.f;;;;
compile;20010321-1.f;;;;
compile;20010426.f;;;;
compile;20010519-1.f;;-std=legacy;;
compile;20020307-1.f;;-std=legacy;;
compile;20030326-1.f;xfail;-pedantic;;
compile;8485.f;;;;
compile;9263.f;xfail;;;
compile;960317-1.f;;;;
compile;970125-0.f;xfail;-w;;
compile;970625-2.f;xfail;;;
compile;970915-0.f;;;;
compile;980310-1.f;;;;
compile;980310-2.f;;;;
compile;980310-3.f;;-std=legacy;;
compile;980310-4.f;;;;
compile;980310-6.f;;;;
compile;980310-7.f;;;;
compile;980310-8.f;;;;
compile;980419-2.f;;-std=legacy;;
compile;980424-0.f;;;;
compile;980427-0.f;;;;
compile;980519-2.f;;;;
compile;980615-0.f;xfail;;;
compile;980616-0.f;xfail;;;
compile;980729-0.f;;;;
compile;981117-1.f;;;;
compile;990115-1.f;;;;
compile;alpha1.f;;;;
compile;check0.f;xfail;-std=legacy;;
compile;cpp.F;;;;
compile;cpp2.F;;;;
compile;cpp6.f;;;;
compile;ffixed-form-1.f;;-ffixed-form;;
compile;ffixed-form-2.f;;-ffixed-form;;
compile;ffixed-line-length-0.f;;-ffixed-line-length-0;;
compile;ffixed-line-length-132.f;;-ffixed-line-length-132;;
compile;ffixed-line-length-72.f;;-ffixed-line-length-72;;
compile;ffixed-line-length-none.f;;-ffixed-line-length-none;;
compile;ffree-form-1.f;;-ffree-form;;
compile;ffree-form-2.f;;-ffree-form;;
compile;ffree-form-3.f;;-ffree-form;;
compile;fno-underscoring.f;;-fno-underscoring;;
compile;funderscoring.f;;-funderscoring;;
compile;pr105203.f;;-O2 -fcompare-debug -ftracer -w;;
compile;pr9258.f;;;;
compile;toon_1.f;;;;
compile;xformat.f;;;;
run;13037.f;;;;
run;1832.f;;-std=legacy;;
run;19981119-0.f;;;;
run;19990313-0.f;;;;
run;19990313-1.f;;;;
run;19990313-2.f;;;;
run;19990313-3.f;;;;
run;19990419-1.f;;;;
run;19990826-0.f;;;;
run;19990826-2.f;;-std=legacy;;
run;20000503-1.f;;;;
run;20001111.f;;;;
run;20010116.f;;-std=legacy;;
run;20010216-1.f;;-ffast-math -march=pentiumpro;;
run;20010426-1.f;;;;
run;20010430.f;;;;
run;20010610.f;;;;
run;6177.f;;;;
run;7388.f;;-fbounds-check;;
run;947.f;;;;
run;970816-3.f;;;;
run;971102-1.f;;;;
run;980520-1.f;;-std=legacy;;
run;980628-0.f;;;;
run;980628-1.f;;;;
run;980628-10.f;;-std=gnu;;
run;980628-2.f;;-std=gnu;;
run;980628-3.f;;-std=gnu;;
run;980628-7.f;;;;
run;980628-8.f;;;;
run;980628-9.f;;-std=gnu;;
run;980701-0.f;;;;
run;980701-1.f;;;;
run;cabs.f;;;;
run;claus.f;;;;
run;complex_1.f;;;;
run;cpp3.F;;-std=legacy;;
run;cpp4.F;;;;
run;cpp5.F;;;;
run;dcomplex.f;;;;
run;dnrm2.f;;-fno-bounds-check;;
run;erfc.f;;;;
run;f77-edit-apostrophe-out.f;;;;
run;f77-edit-colon-out.f;;;;
run;f77-edit-h-out.f;;;;
run;f77-edit-i-in.f;;-std=legacy;;
run;f77-edit-i-out.f;;;;
run;f77-edit-s-out.f;;;;
run;f77-edit-slash-out.f;;;;
run;f77-edit-t-in.f;;-std=legacy;;
run;f77-edit-t-out.f;;;;
run;f77-edit-x-out.f;;;;
run;f90-intrinsic-bit.f;;;;
run;f90-intrinsic-mathematical.f;;;;
run;f90-intrinsic-numeric.f;;;;
run;int8421.f;;;;
run;intrinsic-unix-bessel.f;;;;
run;intrinsic-unix-erf.f;;;;
run;labug1.f;;;;
run;large_vec.f;;;;
run;le.f;;;;
run;short.f;;-std=legacy;;
run;strlen0.f;;-fbounds-check;;