LEVEL = ../../../..

PROG     = fhourstones
CPPFLAGS = -DUNIX -DTRANSIZE=1050011 -DPROBES=8 -DREPORTPLY=8

# Specify which file provides the contents of stdin for the test run 
STDIN_FILENAME = input

RUNTIMELIMIT = 300

include	../Makefile.multisrc
