LEVEL = ../../../../..
PROG     = sgefa
LDFLAGS  = -lm

# This program is adversely effected by the underlying precision of the machine
PROGRAM_IS_NONDETERMINISTIC = 1

include	../../Makefile.multisrc
