#!/usr/bin/env python
# -*- Python -*-

import spec

class SPEC2006_471_omnetpp(spec.TestModule):
    year = '2006'
    category = 'int'
    benchmark = '471.omnetpp'

    train_input_set = ['train/input/omnetpp.ini']
    train_output_set = []
    train_args = ['omnetpp.ini > 471.omnetpp.input1.out 2> 471.omnetpp.input1.err']
    train_cmp_cmds = ['']
    ref_input_set = ['ref/input/omnetpp.ini']
    ref_output_set = []
    ref_args = ['omnetpp.ini > 471.omnetpp.input1.out 2> 471.omnetpp.input1.err']
    ref_cmp_cmds = []

# This is the only required entry point to the module.
test_class = SPEC2006_471_omnetpp

# This is not required, but allows users with LNT in the environment (required
# for initial imports to work) to execute this test directly.
if __name__ == '__main__':
    test_class().main()
