# This file was generated by update-test-config.py
#
# Each line in this file corresponds to a single test. The format of each line
# is:
#
#     <kind>;<sources>;<xfail>;<options>;<enabled-on>;<disabled-on>
#
# where
#
#     <kind>         is one of 'preprocess', 'assemble', 'compile', 'link' or
#                    'run'.
#
#     <sources>      is a space separated list of sources files that comprise
#                    the test. The first file is the "main" file. The rest
#                    of the files must be specified in program compilation
#                    order.
#
#     <xfail>        if present, must be 'xfail' which indicates that the test
#                    is expected to trigger a compile-time or runtime error.
#
#     <options>      is a space separated list of options to be passed to the
#                    compiler when building the test.
#
#     <enabled-on>   is a space-separated list of targets on which the test is
#                    enabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#                    If no targets are provided, the test is enabled on all
#                    targets.
#
#     <disabled-on>  is a space-separated list of targets on which the test is
#                    disabled. Each element of the list will be a regular
#                    expression that is expected to match an LLVM target triple.
#
compile;20080806-1.f90;;;;
compile;actual.f90;;;;
compile;allocate.f90;;;;
compile;ambig.f90;;;;
compile;arrayio.f90;;;;
compile;bergervoet2.f90;;;;
compile;complex_1.f90;;;;
compile;contained_1.f90;;;;
compile;contained_2.f90;;;;
compile;contained_3.f90;;;;
compile;contained_4.f90;;;;
compile;contained_5.f90;;;;
compile;convert.f90;;;;
compile;data_1.f90;;;;
compile;defined_type_1.f90;;;;
compile;defined_type_2.f90;;;;
compile;defined_type_3.f90;;;;
compile;do_1.f90;;;;
compile;dummyfn.f90;;;;
compile;empty.f90;;;;
compile;empty_interface_1.f90;;;;
compile;emptyif-1.f90;;;;
compile;emptyif.f90;;;;
compile;enum_1.f90;;;;
compile;fnresvar.f90;;;;
compile;forall-1.f90;;;;
compile;gen_interf.f90;;;;
compile;implicit.f90;;;;
compile;implicit_1.f90;;;;
compile;implicit_2.f90;;;;
compile;inline_1.f90;;;;
compile;inquiry_1.f90;;;;
compile;io_end.f90;;;;
compile;logical-1.f90;;;;
compile;logical-2.f90;;;;
compile;mloc.f90;;;;
compile;module_common.f90;;;;
compile;module_expr.f90;;;;
compile;module_proc.f90;;;;
compile;module_result.f90;;;;
compile;name_clash.f90;;;;
compile;named_args.f90;;;;
compile;named_args_2.f90;;;;
compile;nested.f90;;;;
compile;noncontinuation_1.f;;;;
compile;parameter_1.f90;;;;
compile;parameter_2.f90;;;;
compile;parameter_3.f90;;;;
compile;pr24136.f;;;;
compile;pr26806.f90;;;;
compile;pr30147.f90;;;;
compile;pr32417.f90;;;;
compile;pr32583.f;;;;
compile;pr32663.f;;;;
compile;pr33276.f90;;;;
compile;pr36078.f90;;;;
compile;pr37236.f;;;;
compile;pr40413.f90;;;;
compile;pr40421.f;;;;
compile;pr40421.f90;;;;
compile;pr41654.f90;;;;
compile;pr42781.f90;;;;
compile;pr45598.f90;;;;
compile;pr45634.f90;;;;
compile;pr45738.f90;;;;
compile;pr49721-1.f;;;;
compile;pr57517.f90;;;;
compile;pr65758.f90;;;;
compile;pr66251-2.f90;;;;
compile;pr66251.f90;;;;
compile;pr66352.f90;;-fprofile-generate;;
compile;pr68639.f90;;;;
compile;pr70960.f90;;;;
compile;pr76490.f90;;;;
compile;pr77798.f90;;;;
compile;pr80158.f;;;;
compile;pr80464.f90;;;;
compile;pr83189.f90;;;;
compile;pr85863.f;;-ffast-math -ftree-vectorize;;
compile;pr85878.f90;;;;
compile;pr88304-2.f90;;;;
compile;pr88304.f90;;;;
compile;pr89324.f90;;;;
compile;shape_reshape.f90;;;;
compile;stoppause.f90;;;;
compile;strparm_1.f90;;;;
compile;transfer-1.f90;;;;
compile;vrp_1.f90;;;;
compile;write.f90;;;;