if (TARGET_OS STREQUAL "OS390")
  list(APPEND CFLAGS -I ${CMAKE_SOURCE_DIR}/MVS)
endif()
add_subdirectory(SubsetARawLoops)
add_subdirectory(SubsetALambdaLoops)
add_subdirectory(SubsetBRawLoops)
add_subdirectory(SubsetBLambdaLoops)
add_subdirectory(SubsetCRawLoops)
add_subdirectory(SubsetCLambdaLoops)
