LEVEL = ../../..
PROG = kc
CPPFLAGS=-I$(BUILD_SRC_DIR) -DYYDEBUG=1
LDFLAGS = -lstdc++
LIBS += -lstdc++
RUN_OPTIONS = -o -v -s kcc $(BUILD_SRC_DIR)/inputs/f3.k $(BUILD_SRC_DIR)/inputs/f2.k $(BUILD_SRC_DIR)/inputs/f1.k
include ../../Makefile.multisrc

