#include <functional>
#include <iostream>
#include <limits>
#include <memory>
#include <random>
#include <stdint.h>

#include "common.h"


// Tests for memory runtime checks generated by the vectorizer. Runs scalar and
// vectorized versions of a loop requiring runtime checks on the same inputs
// with pointers to the same buffer using various offsets between reads and
// writes. Fails if they do not produce the same results.

template <typename Ty>
static void check(const std::unique_ptr<Ty[]> &Reference,
                  const std::unique_ptr<Ty[]> &Tmp, unsigned NumElements,
                  int Offset) {
  if (!std::equal(&Reference[0], &Reference[0] + NumElements, &Tmp[0])) {
    std::cerr << "Miscompare with offset " << Offset << "\n";
    exit(1);
  }
}

// Helper to call \p f with \p args and acts as optimization barrier for \p f.
template <typename F, typename... Args>
__attribute__((optnone)) static void callThroughOptnone(F &&f, Args &&...args) {
  f(std::forward<Args>(args)...);
}

template <typename Ty> using Fn2Ty = std::function<void(Ty *, Ty *, unsigned)>;

// Run both \p ScalarFn and \p VectorFn on the same inputs with pointers to the
// same buffer. Fail if they do not produce the same results.
template <typename Ty>
static void checkOverlappingMemoryOneRuntimeCheck(Fn2Ty<Ty> ScalarFn,
                                                  Fn2Ty<Ty> VectorFn,
                                                  const char *Name) {
  std::cout << "Checking " << Name << "\n";

  unsigned N = 100;
  // Make sure we have enough extra elements so we can be liberal with offsets.
  unsigned NumArrayElements = N * 8;
  std::unique_ptr<Ty[]> Input1(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> Reference(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> ToCheck(new Ty[NumArrayElements]);

  auto CheckWithOffset = [&](int Offset) {
    init_data(Input1, NumArrayElements);
    for (unsigned i = 0; i < NumArrayElements; i++) {
      Reference[i] = Input1[i];
      ToCheck[i] = Input1[i];
    }

    // Run scalar function to generate reference output.
    Ty *ReferenceStart = &Reference[NumArrayElements / 2];
    ScalarFn(ReferenceStart + Offset, ReferenceStart, N);

    // Run vector function to generate output to check.
    Ty *StartPtr = &ToCheck[NumArrayElements / 2];
    callThroughOptnone(VectorFn, StartPtr + Offset, StartPtr, N);

    // Compare scalar and vector output.
    check(Reference, ToCheck, NumArrayElements, Offset);
  };

  for (int i = -100; i <= 100; i++)
    CheckWithOffset(i);
}

template <typename Ty>
using Fn3Ty = std::function<void(Ty *, Ty *, Ty *, unsigned)>;
template <typename Ty>
static void checkOverlappingMemoryTwoRuntimeChecks(Fn3Ty<Ty> ScalarFn,
                                                   Fn3Ty<Ty> VectorFn,
                                                   const char *Name) {
  std::cout << "Checking " << Name << "\n";

  unsigned N = 100;
  // Make sure we have enough extra elements so we can be liberal with offsets.
  unsigned NumArrayElements = N * 8;
  std::unique_ptr<Ty[]> Input1(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> Input2(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> Reference(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> ToCheck(new Ty[NumArrayElements]);

  auto CheckWithOffsetSecond = [&](int Offset) {
    init_data(Input1, NumArrayElements);
    init_data(Input2, NumArrayElements);
    for (unsigned i = 0; i < NumArrayElements; i++) {
      Reference[i] = Input1[i];
      ToCheck[i] = Input1[i];
    }

    // Run scalar function to generate reference output.
    Ty *ReferenceStart = &Reference[NumArrayElements / 2];
    ScalarFn(ReferenceStart + Offset, &Input2[0], ReferenceStart, N);

    // Run vector function to generate output to check.
    Ty *StartPtr = &ToCheck[NumArrayElements / 2];
    callThroughOptnone(VectorFn, StartPtr + Offset, &Input2[0], StartPtr, N);

    // Compare scalar and vector output.
    check(Reference, ToCheck, NumArrayElements, Offset);
  };

  for (int i = -100; i <= 100; i++)
    CheckWithOffsetSecond(i);
}



template <typename Ty>
using Fn4Ty = std::function<void(Ty *, Ty *, unsigned, unsigned)>;
template <typename Ty>
static void checkOverlappingMemoryTwoRuntimeChecksNested(Fn4Ty<Ty> ScalarFn,
                                                         Fn4Ty<Ty> VectorFn,
                                                         const int OuterTC,
                                                         const int InnerTC,
                                                         const char *Name) {
  std::cout << "Checking " << Name << "\n";

  // Make sure we have enough extra elements so we can be liberal with offsets.
  const unsigned NumArrayElements = (InnerTC * (OuterTC + 1)) * 8;
  std::unique_ptr<Ty[]> Input1(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> Reference(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> ToCheck(new Ty[NumArrayElements]);

  auto CheckWithOffsetSecond = [&](int Offset) {
    init_data(Input1, NumArrayElements);
    for (unsigned i = 0; i < NumArrayElements; i++) {
      Reference[i] = Input1[i];
      ToCheck[i] = Input1[i];
    }

    // Run scalar function to generate reference output.
    Ty *ReferenceStart = &Reference[NumArrayElements / 2];
    ScalarFn(ReferenceStart + Offset, ReferenceStart, OuterTC, InnerTC);

    // Run vector function to generate output to check.
    Ty *StartPtr = &ToCheck[NumArrayElements / 2];
    callThroughOptnone(VectorFn, StartPtr + Offset, StartPtr, OuterTC, InnerTC);

    // Compare scalar and vector output.
    check(Reference, ToCheck, NumArrayElements, Offset);
  };

  // With a nested loop, sometimes the runtime checks will fail and sometimes
  // succeed. For example, with large offsets you'd expect for the first and
  // last one or two executions of the inner loop there is no overlap.
  for (int i = -(2 * (InnerTC + 1)); i <= (2 * (InnerTC + 1)); i++)
    CheckWithOffsetSecond(i);
}

#define DEFINE_SCALAR_AND_VECTOR_STENCIL_FN(Loop)                              \
  auto ScalarFn = [](auto *Out, auto *In, unsigned TC, long S1, long S2) {     \
    _Pragma("clang loop vectorize(disable) interleave_count(1)") Loop          \
  };                                                                           \
  auto VectorFn = [](auto *Out, auto *In, unsigned TC, long S1, long S2) {     \
    _Pragma("clang loop vectorize(enable)") Loop                               \
  };

template <typename Ty>
using StencilFnTy = std::function<void(Ty *, Ty *, unsigned, long, long)>;

template <typename Ty>
static void
checkOverlappingMemoryStencil(StencilFnTy<Ty> ScalarFn,
                              StencilFnTy<Ty> VectorFn, const char *Name,
                              const char *TypeName, long S1, long S2) {
  std::cout << "Checking " << Name << ", " << TypeName << ", strides " << S1
            << " and " << S2 << "\n";

  unsigned N = 64;
  // Conservative bound on the read offsets for the stencil loops below.
  unsigned Reach = 2 * (S1 + S2) + 1;
  // Cover all possible overlap and include disjoint accesses. Test at least
  // offsets -100 to 100.
  int MaxOffset = std::max(100u, Reach + N + 2);
  // The buffer must hold Out at every offset and every read of In.
  unsigned Margin = MaxOffset + N;
  unsigned NumArrayElements = 2 * Margin + 1;
  std::unique_ptr<Ty[]> Input(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> Reference(new Ty[NumArrayElements]);
  std::unique_ptr<Ty[]> ToCheck(new Ty[NumArrayElements]);
  init_data(Input, NumArrayElements);

  auto CheckWithOffset = [&](int Offset) {
    for (unsigned i = 0; i < NumArrayElements; i++) {
      Reference[i] = Input[i];
      ToCheck[i] = Input[i];
    }

    // Run scalar function to generate reference output.
    Ty *ReferenceStart = &Reference[Margin];
    ScalarFn(ReferenceStart + Offset, ReferenceStart, N, S1, S2);

    // Run vector function to generate output to check.
    Ty *StartPtr = &ToCheck[Margin];
    callThroughOptnone(VectorFn, StartPtr + Offset, StartPtr, N, S1, S2);

    // Compare scalar and vector output.
    check(Reference, ToCheck, NumArrayElements, Offset);
  };

  for (int Offset = -MaxOffset; Offset <= MaxOffset; Offset++)
    CheckWithOffset(Offset);
}

// Check all element types with one stride. The loops get 0 as their second
// stride and do not use it.
template <typename ScalarFnTy, typename VectorFnTy>
static void checkOneStride(ScalarFnTy ScalarFn, VectorFnTy VectorFn,
                           const char *Name) {
  for (long S : {1, 2, 7, 16, 64, 100}) {
    checkOverlappingMemoryStencil<uint8_t>(ScalarFn, VectorFn, Name, "uint8_t",
                                           S, 0);
    checkOverlappingMemoryStencil<uint32_t>(ScalarFn, VectorFn, Name,
                                            "uint32_t", S, 0);
    checkOverlappingMemoryStencil<uint64_t>(ScalarFn, VectorFn, Name,
                                            "uint64_t", S, 0);
  }
}

// Check all element types with two strides. Try each pair in both orders,
// because either stride can be the larger one.
template <typename ScalarFnTy, typename VectorFnTy>
static void checkTwoStrides(ScalarFnTy ScalarFn, VectorFnTy VectorFn,
                            const char *Name) {
  std::pair<long, long> Strides[] = {{1, 2},    {2, 1},    {7, 16}, {16, 7},
                                     {16, 100}, {100, 16}, {64, 64}};
  for (auto [S1, S2] : Strides) {
    checkOverlappingMemoryStencil<uint8_t>(ScalarFn, VectorFn, Name, "uint8_t",
                                           S1, S2);
    checkOverlappingMemoryStencil<uint32_t>(ScalarFn, VectorFn, Name,
                                            "uint32_t", S1, S2);
    checkOverlappingMemoryStencil<uint64_t>(ScalarFn, VectorFn, Name,
                                            "uint64_t", S1, S2);
  }
}

int main(void) {
  rng = std::mt19937(15);

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      for (unsigned i = 0; i < TC; i++)
        A[i] = B[i] + 10;
    );

    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn, "1 read, 1 write, step 1, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(ScalarFn, VectorFn,
                                               "1 read, 1 write, step 1, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn, "1 read, 1 write, step 1, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      for (unsigned i = 0; i < TC; i++)
        A[i] = B[i + 3] + 10;
    );

    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn, "1 read, 1 write, offset 3, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(
        ScalarFn, VectorFn, "1 read, 1 write, offset 3, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn, "1 read, 1 write, offset 3, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      for (unsigned i = 3; i < TC; i++)
        A[i] = B[i - 3] + 10;
    );

    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn, "1 read, 1 write, offset -3, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(
        ScalarFn, VectorFn, "1 read, 1 write, offset -3, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn, "1 read, 1 write, offset -3, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      for (unsigned i = TC; i > 0; i--)
        A[i] = B[i] + 10;);

    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn, "1 read, 1 write, index count down, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(
        ScalarFn, VectorFn, "1 read, 1 write, index count down, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn, "1 read, 1 write, index count down, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      for (unsigned i = TC; i > 2; i -= 2)
        A[i] = B[i] + 10;
    );

    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn, "1 read, 1 write, index count down 2, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(
        ScalarFn, VectorFn, "1 read, 1 write, index count down 2, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn, "1 read, 1 write, index count down 2, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      for (unsigned i = 0, j = 0; i < TC; i++) {
        A[i] = B[j] + 10;
        j += 2;
      }
    );
    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn,
        "1 read, 1 write, 2 inductions, different steps, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(
        ScalarFn, VectorFn,
        "1 read, 1 write, 2 inductions, different steps, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn,
        "1 read, 1 write, 2 inductions, different steps, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      _Pragma("clang loop unroll(disable)")
      for (unsigned i = 0; i < TC; i += 2)
        A[i] = B[i] + 10;
    );

    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn, "1 read, 1 write, induction increment 2, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(
        ScalarFn, VectorFn, "1 read, 1 write, induction increment 2, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn,
        "1 read, 1 write, induction increment 2, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN2(,
      for (unsigned i = 0, sum = 0; i < TC; i++) {
        sum += A[i] + 10;
        B[TC / 2] = sum;
      }
    );

    checkOverlappingMemoryOneRuntimeCheck<uint8_t>(
        ScalarFn, VectorFn, "1 read, 1 write to invariant address, step 1, uint8_t");
    checkOverlappingMemoryOneRuntimeCheck<uint32_t>(
        ScalarFn, VectorFn, "1 read, 1 write to invariant address, step 1, uint32_t");
    checkOverlappingMemoryOneRuntimeCheck<uint64_t>(
        ScalarFn, VectorFn, "1 read, 1 write to invariant address, step 1, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN3(
      for (unsigned i = 0; i < TC; i++)
        A[i] = B[i] + C[i] + 10;
    );

    checkOverlappingMemoryTwoRuntimeChecks<uint32_t>(
        ScalarFn, VectorFn, "2 reads, 1 write, simple indices, uint32_t");
    checkOverlappingMemoryTwoRuntimeChecks<uint8_t>(
        ScalarFn, VectorFn, "2 reads, 1 write, simple indices, uint8_t");
    checkOverlappingMemoryTwoRuntimeChecks<uint64_t>(
        ScalarFn, VectorFn, "2 reads, 1 write, simple indices, uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_FN3(
      for (unsigned i = 0; i < TC; i++) {
        auto X = C[i] + 10;
        A[i] = X;
        B[i] = X + 9;
      }
    );

    checkOverlappingMemoryTwoRuntimeChecks<uint8_t>(
        ScalarFn, VectorFn, "1 read, 2 writes, simple indices, uint8_t");
    checkOverlappingMemoryTwoRuntimeChecks<uint32_t>(
        ScalarFn, VectorFn, "1 read, 2 writes, simple indices, uint32_t");
    checkOverlappingMemoryTwoRuntimeChecks<uint64_t>(
        ScalarFn, VectorFn, "1 read, 2 writes, simple indices, uint64_t");
  }

  {
    DEFINE_NESTED_SCALAR_AND_VECTOR_FN4(
        auto X = B[(i * OuterTC) + j];
        A[(i * (OuterTC + 1)) + j] = X;
    );
    checkOverlappingMemoryTwoRuntimeChecksNested<uint8_t>(
        ScalarFn, VectorFn, 100, 100, "1 read, 1 write, nested loop (matching trip counts), uint8_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint32_t>(
        ScalarFn, VectorFn, 100, 100, "1 read, 1 write, nested loop (matching trip counts), uint32_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint64_t>(
        ScalarFn, VectorFn, 100, 100, "1 read, 1 write, nested loop (matching trip counts), uint64_t");

    checkOverlappingMemoryTwoRuntimeChecksNested<uint8_t>(
        ScalarFn, VectorFn, 100, 50, "1 read, 1 write, nested loop (different trip counts), uint8_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint32_t>(
        ScalarFn, VectorFn, 100, 50, "1 read, 1 write, nested loop (different trip counts), uint32_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint64_t>(
        ScalarFn, VectorFn, 100, 50, "1 read, 1 write, nested loop (different trip counts), uint64_t");
  }

  {
    DEFINE_NESTED_SCALAR_AND_VECTOR_FN4(
        auto X = B[(i * OuterTC) + j];
        A[(i * (OuterTC + 1)) + j] += X;
    );

    checkOverlappingMemoryTwoRuntimeChecksNested<uint8_t>(
        ScalarFn, VectorFn, 100, 100, "2 reads, 1 write, nested loop (matching trip counts), uint8_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint32_t>(
        ScalarFn, VectorFn, 100, 100, "2 reads, 1 write, nested loop (matching trip counts), uint32_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint64_t>(
        ScalarFn, VectorFn, 100, 100, "2 reads, 1 write, nested loop (matching trip counts), uint64_t");

    checkOverlappingMemoryTwoRuntimeChecksNested<uint8_t>(
        ScalarFn, VectorFn, 100, 50, "2 reads, 1 write, nested loop (different trip counts), uint8_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint32_t>(
        ScalarFn, VectorFn, 100, 50, "2 reads, 1 write, nested loop (different trip counts), uint32_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint64_t>(
        ScalarFn, VectorFn, 100, 50, "2 reads, 1 write, nested loop (different trip counts), uint64_t");
  }

  {
    DEFINE_NESTED_SCALAR_AND_VECTOR_FN5(
        auto X = B[(i * OuterTC) + j];
        A[(i * (OuterTC + 1)) + j] = X;
    );
    checkOverlappingMemoryTwoRuntimeChecksNested<uint8_t>(
        ScalarFn, VectorFn, 100, 100, "1 read, 1 write, nested loop (decreasing outer iv, matching trip counts), uint8_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint32_t>(
        ScalarFn, VectorFn, 100, 100, "1 read, 1 write, nested loop (decreasing outer iv, matching trip counts), uint32_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint64_t>(
        ScalarFn, VectorFn, 100, 100, "1 read, 1 write, nested loop (decreasing outer iv, matching trip counts), uint64_t");
  }

  {
    DEFINE_NESTED_SCALAR_AND_VECTOR_FN5(
        auto X = B[(i * OuterTC) + j];
        A[(i * (OuterTC + 1)) + j] += X;
    );

    checkOverlappingMemoryTwoRuntimeChecksNested<uint8_t>(
        ScalarFn, VectorFn, 100, 100, "2 reads, 1 write, nested loop (decreasing outer iv, matching trip counts), uint8_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint32_t>(
        ScalarFn, VectorFn, 100, 100, "2 reads, 1 write, nested loop (decreasing outer iv, matching trip counts), uint32_t");
    checkOverlappingMemoryTwoRuntimeChecksNested<uint64_t>(
        ScalarFn, VectorFn, 100, 100, "2 reads, 1 write, nested loop (decreasing outer iv, matching trip counts), uint64_t");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_STENCIL_FN(
      for (long i = 0; i < TC; i++)
        Out[i] = In[i - S1] + In[i - 1] + In[i] + In[i + 1] + In[i + S1];
    );
    checkOneStride(ScalarFn, VectorFn, "1D 5-point stencil");
  }

  {
    DEFINE_SCALAR_AND_VECTOR_STENCIL_FN(
      for (long i = 0; i < TC; i++)
        Out[i] = In[i - 2 * S1] + In[i - S1] + In[i] + In[i + S1] +
                 In[i + 2 * S1];
    );
    checkOneStride(ScalarFn, VectorFn, "stencil with scaled stride");
  }

  {
    // A 3D-style stencil. S1 is the row size and S2 is the plane size.
    DEFINE_SCALAR_AND_VECTOR_STENCIL_FN(
      for (long i = 0; i < TC; i++)
        Out[i] = In[i - S2 - S1] + In[i - S2] + In[i - S2 + S1] + In[i - S1] +
                 In[i] + In[i + S1] + In[i + S2 - S1] + In[i + S2] +
                 In[i + S2 + S1];
    );
    checkTwoStrides(ScalarFn, VectorFn, "3D-style stencil with two strides");
  }

  {
    // Either In[i - 2 * S1] or In[i - 2 * S2] can be the lowest read. It
    // depends on the strides at runtime. In the same way, either In[i + 2 * S1]
    // or In[i + 2 * S2] can be the highest read.
    DEFINE_SCALAR_AND_VECTOR_STENCIL_FN(
      for (long i = 0; i < TC; i++)
        Out[i] = In[i - 2 * S2] + In[i - 2 * S1] + In[i - S2] + In[i - S1] +
                 In[i] + In[i + S1] + In[i + S2] + In[i + 2 * S1] +
                 In[i + 2 * S2];
    );
    checkTwoStrides(ScalarFn, VectorFn, "stencil with two scaled strides");
  }

  return 0;
}
