# SingleSource/UnitTests/Vector/AArch64/Makefile

DIRS = 
LEVEL = ../../../..

ifdef BENCHMARKING_ONLY
PROGRAMS_TO_SKIP += aarch64_neon_intrinsics
endif

include $(LEVEL)/SingleSource/Makefile.singlesrc

CFLAGS += -std=c99
