LEVEL = ../../../..
PROG = bisect
LDFLAGS = -lm
#RUN_OPTIONS += 
INPUT_FILENAME = bisect_test.in

# This program is adversely effected by the underlying precision of the machine
PROGRAM_IS_NONDETERMINISTIC = 1

include ../Makefile.multisrc

